# Name of the site (displayed in the header)
name: Nidhin Benjamine

# Short bio or description (displayed in the header)
description:

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/870715?s=400&u=4356646c079ef07c94bfb57f6217e96b6c8ef3b7&v=4

disqus: NBenjamin

# Includes an icon in the footer for each username you enter
footer-links:
  email: nbenjamine@gmail.com
  github: nbenjamin
  linkedin: nidhin-benjamine-9a395314
  twitter: nidhinbenjamin

url: http://nbenjamin.tech

baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink:            pretty

markdown:             kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

sass:
  style: :compressed # expanded or compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
